<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cart_customize_model extends MY_Model
{

    protected $_table_name = 'cart_customize';
    public $id    = 'id_cart_customize';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    public function insert_customize($data,$batch=FALSE){
		if($batch == TRUE){
			$this->db->insert_batch($this->_table_name, $data);
			// $this->db->insert_batch('tbl_users',$data);
		}
		else{
			$this->db->set($data);
			$this->db->insert($this->_table_name);
			$id = $this->db->insert_id();
			return $id;
		}
	}

	function get_customize($id_cart)
    {
        $this->db->where('id_cart', $id_cart);
        return $this->db->get($this->_table_name)->result();
    }

    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->_table_name);
    }

}

/* End of file Detail_order_model.php */
/* Location: ./application/models/Detail_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */