<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_order_model extends CI_Model
{

    public $_table_name = 'detail_order';
    public $id_detail_order = 'id_detail_order';
    public $id_data_order ='id_data_order';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    // get data by id
    function get_by_id_order($id_data_order)
    {   
        $this->db->join('data_order','detail_order.id_data_order=data_order.id_data_order');
        $this->db->join('produk','detail_order.id_produk=produk.id_produk');
        $this->db->join('packaging','detail_order.id_packaging=packaging.id_packaging','left');
        $this->db->where('detail_order.id_data_order', $id_data_order);
        return $this->db->get($this->_table_name)->result();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->_table_name, $data);
        $id = $this->db->insert_id();
        return (isset($id)) ? $id : FALSE;
    }

    // update data
    function update($id_detail_order, $data)
    {
        $this->db->where($this->id_detail_order, $id_detail_order);
        $this->db->update($this->_table_name, $data);
    }

    function delete($id_detail_order)
    {
        $this->db->where($this->id_detail_order, $id_detail_order);
        $this->db->delete($this->_table_name);
    }


}

/* End of file Detail_order_model.php */
/* Location: ./application/models/Detail_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */