<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Konf_pembayaran_model extends CI_Model
{

    public $_table_name = 'konfirmasi_pembayaran';
    public $id = 'id_konfirmasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    function get_belum_selesai()
    {
        $this->db->where('status_konfirmasi','menunggu konfirmasi');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->_table_name)->result();
    }

    function get_selesai()
    {
        $this->db->where('status_konfirmasi','sudah bayar');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->_table_name)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('data_order', 'data_order.id_data_order=konfirmasi_pembayaran.id_data_order');
        $this->db->where($this->id, $id);
        return $this->db->get($this->_table_name)->row();
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->_table_name, $data);
        $id = $this->db->insert_id();
        return $id;
    }

    function count_konfirmasi_pembayaran()
    {//untuk menampilkan konfirmasi pembayaran pada sidebar
        $this->db->where('status_konfirmasi','menunggu konfirmasi');
        $this->db->from('konfirmasi_pembayaran');
        return $this->db->count_all_results();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->_table_name, $data);
    }

    function cek_duplicate_entry($id_data_order)
    {
        $this->db->where('id_data_order', $id_data_order);
        return $this->db->get($this->_table_name)->result();
    }

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */