<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Order_customize_model extends MY_Model
{

    protected $_table_name = 'order_customize';
    public $id    = 'id_order_customize';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_by_id_data_order($id_data_order)
    {
    	$this->db->join('detail_order','order_customize.id_detail_order=detail_order.id_detail_order');
    	$this->db->where('id_data_order',$id_data_order);
        return $this->db->get($this->_table_name)->result();

    }
}

/* End of file Detail_order_model.php */
/* Location: ./application/models/Detail_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */