<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Packaging_model extends MY_Model
{

    protected $_table_name  = 'packaging';
    protected $_primary_key = 'id_packaging';
    public $id    = 'id_packaging';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_by_id($id_packaging)
    {
        $this->db->where('id_packaging', $id_packaging);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->_table_name)->row();
    }

}

/* End of file Detail_order_model.php */
/* Location: ./application/models/Detail_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */