<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Slider_model extends CI_Model
{
    function get_slider()
    {
        $this->db->order_by('id_slider', 'DESC');
        $this->db->where('status_slider', 'aktif');
        return $this->db->get('slider')->result();
    }

    function get_slider_list()//untuk tabel nama slider pada bagian bawah
    {
        $this->db->order_by('id_slider', 'DESC');
        return $this->db->get('slider')->result();
    }

    function get_by_id($id_slider)
    {
        $this->db->where('id_slider', $id_slider);
        return $this->db->get('slider')->row();
    }

    function insert($data)
    {
        $this->db->insert('slider', $data);
    }

    // update data
    function update($id_slider, $data)
    {
        $this->db->where('id_slider', $id_slider);
        $this->db->update('slider', $data);
    }

    //delete data
    function delete_slider($id_slider)
    {
        $this->db->where('id_slider', $id_slider);
        return $this->db->delete('slider');
    }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-18 12:43:15 */
/* http://harviacode.com */